package me.abab.QWQTECH.utils;

import io.github.thebusybiscuit.slimefun4.api.items.ItemGroup;
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack;
import io.github.thebusybiscuit.slimefun4.api.items.groups.NestedItemGroup;
import io.github.thebusybiscuit.slimefun4.api.items.groups.SubItemGroup;
import io.github.thebusybiscuit.slimefun4.libraries.dough.items.CustomItemStack;
import me.abab.QWQTECH.QWQTECH;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.ItemStack;
import io.github.thebusybiscuit.slimefun4.utils.SlimefunUtils;

public class Items {
    public static final ItemGroup QWQTECH_MAIN = new NestedItemGroup(new NamespacedKey(QWQTECH.getInstance(), "QWQTECH_MAIN"), new CustomItemStack(Material.AMETHYST_CLUSTER, "&x&f&f&f&f&f&fQ&x&f&f&e&3&f&fW&x&f&f&c&6&f&fQ&x&f&f&a&a&f&fT&x&f&f&8&e&f&fE&x&f&f&7&1&f&fC&x&f&f&5&5&f&fH", "&x&f&f&f&f&f&fq&x&f&f&e&e&c&cw&x&f&f&d&d&9&9q&x&f&f&c&c&6&6!&x&f&f&b&b&3&3!&x&f&f&a&a&0&0!"));
    public static final ItemGroup QWQTECH_SNAKE = new SubItemGroup(new NamespacedKey(QWQTECH.getInstance(), "QWQTECH_SNAKE"),(NestedItemGroup) QWQTECH_MAIN, new CustomItemStack(Material.NETHER_STAR, "&x&f&f&5&5&f&f&lQ&x&e&c&5&5&f&f&lW&x&d&9&5&5&f&f&lQ&x&c&6&5&5&f&f&lT&x&b&3&5&5&f&f&lE&x&a&1&5&5&f&f&lC&x&8&e&5&5&f&f&lH&x&7&b&5&5&f&f&l_&x&6&8&5&5&f&f&l蛇&x&5&5&5&5&f&f&l窝"));
    public static final ItemGroup QWQTECH_ITEM = new SubItemGroup(new NamespacedKey(QWQTECH.getInstance(), "QWQTECH_ITEM"), (NestedItemGroup) QWQTECH_MAIN, new CustomItemStack(Material.NETHERITE_INGOT, "&x&a&a&a&a&a&aQ&x&b&3&b&3&b&3W&x&b&d&b&d&b&dQ&x&c&6&c&6&c&6T&x&d&0&d&0&d&0E&x&d&9&d&9&d&9C&x&e&3&e&3&e&3H&x&e&c&e&c&e&c-&x&f&6&f&6&f&6物&x&f&f&f&f&f&f品"));
    public static final ItemGroup QWQTECH_TOOL = new SubItemGroup(new NamespacedKey(QWQTECH.getInstance(), "QWQTECH_TOOL"), (NestedItemGroup) QWQTECH_MAIN, new CustomItemStack(Material.NETHERITE_PICKAXE, "&x&f&f&a&a&0&0Q&x&e&c&b&3&0&9W&x&d&9&b&d&1&3Q&x&c&6&c&6&1&cT&x&b&3&d&0&2&6E&x&a&1&d&9&2&fC&x&8&e&e&3&3&9H&x&7&b&e&c&4&2-&x&6&8&f&6&4&c工&x&5&5&f&f&5&5具"));
    public static ItemStack QWQ_DOWEL = new CustomItemStack(Material.END_ROD, "&x&5&5&f&f&5&5基&x&5&5&f&f&8&0础&x&5&5&f&f&a&a传&x&5&5&f&f&d&4动&x&5&5&f&f&f&f杆", "", "&x&f&f&f&f&5&5Q&x&e&3&f&f&7&1W&x&c&6&f&f&8&eQ&x&a&a&f&f&a&aT&x&8&e&f&f&c&6E&x&7&1&f&f&e&3C&x&5&5&f&f&f&fH","");
    public static ItemStack QWQ_DOWEL_PLUS = new CustomItemStack(Material.LIGHTNING_ROD, "&x&f&f&5&5&f&f&l高&x&f&f&5&5&d&4&l级&x&f&f&5&5&a&a&l传&x&f&f&5&5&8&0&l动&x&f&f&5&5&5&5&l杆", "", "&x&5&5&f&f&5&5&l更&x&8&e&f&f&5&5&l加&x&c&6&f&f&5&5&l坚&x&f&f&f&f&5&5&l固", "&x&f&f&f&f&5&5Q&x&e&3&f&f&7&1W&x&c&6&f&f&8&eQ&x&a&a&f&f&a&aT&x&8&e&f&f&c&6E&x&7&1&f&f&e&3C&x&5&5&f&f&f&fH", "");
    public static ItemStack QWQ_BILIBILI_PINK = new CustomItemStack(Material.PINK_BED, "&x&f&f&5&5&f&fBILIBILI-粉", "", "&x&f&f&5&5&f&f(゜-゜)つロ 干杯", "&x&f&f&f&f&5&5Q&x&e&3&f&f&7&1W&x&c&6&f&f&8&eQ&x&a&a&f&f&a&aT&x&8&e&f&f&c&6E&x&7&1&f&f&e&3C&x&5&5&f&f&f&fH", "");
    public static ItemStack QWQ_BILIBILI_BLUE = new CustomItemStack(Material.BLUE_BED, "&x&5&5&f&f&f&fBILIBILI-蓝", "", "&x&5&5&f&f&f&f(゜-゜)つロ 干杯", "&x&f&f&f&f&5&5Q&x&e&3&f&f&7&1W&x&c&6&f&f&8&eQ&x&a&a&f&f&a&aT&x&8&e&f&f&c&6E&x&7&1&f&f&e&3C&x&5&5&f&f&f&fH", "");
    public static ItemStack QWQ_BILIBILI = new CustomItemStack(Material.END_CRYSTAL, "&x&5&5&f&f&f&fb&x&6&a&e&a&f&fi&x&8&0&d&4&f&fl&x&9&5&b&f&f&fi&x&a&a&a&a&f&fb&x&b&f&9&5&f&fi&x&d&4&8&0&f&fl&x&e&a&6&a&f&fi&x&f&f&5&5&f&f?", "", "&x&5&5&f&f&f&f(&x&6&a&e&a&f&f゜&x&8&0&d&4&f&f-&x&9&5&b&f&f&f゜&x&a&a&a&a&f&f)&x&b&f&9&5&f&fつ&x&d&4&8&0&f&fロ&x&e&a&6&a&f&f干&x&f&f&5&5&f&f杯", "&x&5&5&f&f&f&f右&x&7&7&d&d&f&f键&x&9&9&b&b&f&f来&x&b&b&9&9&f&f玩&x&d&d&7&7&f&f玩&x&f&f&5&5&f&f?", "&x&f&f&f&f&f&fQ&x&f&f&f&0&f&fW&x&f&f&e&0&f&fQ&x&f&f&d&1&f&fT&x&f&f&c&1&f&fE&x&f&f&b&2&f&fC&x&f&f&a&2&f&fH&x&f&f&9&3&f&f-&x&f&f&8&3&f&fT&x&f&f&7&4&f&fO&x&f&f&6&4&f&fO&x&f&f&5&5&f&fL", "");
    public static ItemStack QWQ_HUZTOPRE_QWQ = new CustomItemStack(SlimefunUtils.getCustomHead("ewogICJ0aW1lc3RhbXAiIDogMTcyMDIzODIzNzUyNywKICAicHJvZmlsZUlkIiA6ICIwNWMwMzk1NDA3YTg0NjExOGZkYzdiOWQ3ZGE2OTRiYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJIdVpUMHByZV9xd3EiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2JlNGVjOWZiZWRmMDJjMzYyNzg1N2E5YmQwNzQ3YjU1MmRjYWYyMjFjNjYwMGQ5NzJjODliOGMyMzk3OTBhZiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"), "&x&f&f&f&f&5&5&lH&x&f&0&f&f&6&4&lu&x&e&0&f&f&7&4&lZ&x&d&1&f&f&8&3&lT&x&c&1&f&f&9&3&l0&x&b&2&f&f&a&2&lp&x&a&2&f&f&b&2&lr&x&9&3&f&f&c&1&le&x&8&3&f&f&d&1&l_&x&7&4&f&f&e&0&lq&x&6&4&f&f&f&0&lw&x&5&5&f&f&f&f&lq", "", "&x&f&f&f&f&5&5&m我&x&e&c&f&f&6&8&m爱&x&d&9&f&f&7&b&m写&x&c&6&f&f&8&e&m赤&x&b&3&f&f&a&1&m石&x&a&1&f&f&b&3&m科&x&8&e&f&f&c&6&m技&x&7&b&f&f&d&9&m!&x&6&8&f&f&e&c&m!&x&5&5&f&f&f&f&m!", "&x&f&f&5&5&f&f&lQ&x&e&c&5&5&f&f&lW&x&d&9&5&5&f&f&lQ&x&c&6&5&5&f&f&lT&x&b&3&5&5&f&f&lE&x&a&1&5&5&f&f&lC&x&8&e&5&5&f&f&lH&x&7&b&5&5&f&f&l_&x&6&8&5&5&f&f&l蛇&x&5&5&5&5&f&f&l窝", "");
    public static ItemStack QWQ_DEV_DASHE = new CustomItemStack(SlimefunUtils.getCustomHead("ewogICJ0aW1lc3RhbXAiIDogMTcyMDI0MjQzMDIxNCwKICAicHJvZmlsZUlkIiA6ICI5ZDJhNGU4NjNhMjA0Njc0YTNjNjJlZmEwYWJiYTYwOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJEZXZpSUd1Z1kiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTkwNzQwYTk5MjIzNjU2MjYwOWU0NGQzOGNlMzRjYmY3MmFlNDY3ZTY1NWJlYzQwZTZmZTRjOWIwZThjY2Q1YyIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"), "&x&a&a&a&a&a&a&lD&x&b&5&b&5&b&5&le&x&b&f&b&f&b&f&lv&x&c&a&c&a&c&a&li&x&d&4&d&4&d&4&lI&x&d&f&d&f&d&f&lG&x&e&a&e&a&e&a&lu&x&f&4&f&4&f&4&lg&x&f&f&f&f&f&f&lY", "", "&x&f&f&5&5&5&5&l沉&x&f&f&6&6&4&4&l淀&x&f&f&7&7&3&3&l刷&x&f&f&8&8&2&2&l物&x&f&f&9&9&1&1&l大&x&f&f&a&a&0&0&l蛇", "&x&f&f&5&5&f&f&lQ&x&e&c&5&5&f&f&lW&x&d&9&5&5&f&f&lQ&x&c&6&5&5&f&f&lT&x&b&3&5&5&f&f&lE&x&a&1&5&5&f&f&lC&x&8&e&5&5&f&f&lH&x&7&b&5&5&f&f&l_&x&6&8&5&5&f&f&l蛇&x&5&5&5&5&f&f&l窝", "");
    public static ItemStack QWQ_KALEINEXD_DASHE = new CustomItemStack(SlimefunUtils.getCustomHead("ewogICJ0aW1lc3RhbXAiIDogMTcyMDI0Mjk4ODIyMywKICAicHJvZmlsZUlkIiA6ICJmYmYzYTVjMmJmM2Y0YjU2OWMyNTI2YzRlYzlhZDZjMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJLYWxlaW5lWEQiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWZkNDczOTc0NzUxYjU2MTY2Njg3NDJjODI4ZmQ3OTc5Y2YyOWQyNDFjZmEyMTA4OGYyNjYwYzA4NTZjMjc2IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTY5YjdmMmExZDAwZDI2ZjMwZWZlM2Y5YWI5YWM4MTdiMWU2ZDM1ZjRmM2NmYjAzMjRlZjJkMzI4MjIzZDM1MCIKICAgIH0KICB9Cn0="), "&x&f&f&5&5&f&f&lK&x&f&f&5&5&f&4&la&x&f&f&5&5&e&a&ll&x&f&f&5&5&d&f&le&x&f&f&5&5&d&4&li&x&f&f&5&5&c&a&ln&x&f&f&5&5&b&f&le&x&f&f&5&5&b&5&lX&x&f&f&5&5&a&a&lD", "", "&x&f&f&5&5&5&5&l飞&x&f&f&6&3&4&7&l &x&f&f&7&1&3&9&l龙&x&f&f&8&0&2&b&l &x&f&f&8&e&1&c&l在&x&f&f&9&c&0&e&l &x&f&f&a&a&0&0&l天", "&x&f&f&5&5&f&f&lQ&x&e&c&5&5&f&f&lW&x&d&9&5&5&f&f&lQ&x&c&6&5&5&f&f&lT&x&b&3&5&5&f&f&lE&x&a&1&5&5&f&f&lC&x&8&e&5&5&f&f&lH&x&7&b&5&5&f&f&l_&x&6&8&5&5&f&f&l蛇&x&5&5&5&5&f&f&l窝", "");
}
